---
title: "Publications"
output: 
  html_document:
   toc: false
   logo: img/LogoINRAE-MIA.jpg
   number_sections: false
   highlight: tango
   css: style.css
   includes:
     before_body: extlogo.html
---

<br>
*Last update on `r format(Sys.time(), '%d/%m/%y')` *

<br>

## Submitted papers




- [S1] *Auto-encoding GPS data to reveal individual and collective behaviour*, S.C. Chabert-Liddell, N. Bez, P. Gloaguen, S. Donnet , S. Mahévas.  [Submitted](https://hal.science/hal-04317516)

- [S2] *Climatic legacies drive spatial aggregation of plants in drylands*, B. Pichon,   S. Kéfi, I. Gounand,  S. Donnet. Submitted

- [S3] *Common Structure Discovery in Collections of Bipartite Networks: Application to Pollination Systems*, L. Lacoste, P. Barbillon, S. Donnet. [Submitted](https://hal.inrae.fr/MIA-PARIS/hal-05399136v1)

- [S4] *Inferring the presence and abundance of rare waterbirds species from scarce data*, 
B. Bricout, L. Dami, P. Defos du Rau, S. Donnet, T. Galewski, S. Robin. [Submitted](https://arxiv.org/abs/2602.10673)

<br>



## Published or accepted articles

- [A30]  *Estimating distances to tipping points from dryland ecosystem images*, B. Pichon,  S. Donnet, I. Gounand,  S. Kéfi. [Accepted for publication in Methods in Ecology and evolution](https://www.biorxiv.org/content/10.1101/2024.02.20.581244v1) 

- [A29] *Grazing modulates the multiscale spatial structure of dryland vegetation*. Benoît Pichon, S. Kéfi, I. Gounand N. Gross, Y. Le Bagousse-Pinguet Josquin Guerber, David Eldridge, Enrique Valencia, César Plaza, Jaime Martínez-Valderrama, Hugo Saiz, Victoria Ochoa, Beatriz Gozalo, Emilio Guirado, Miguel García-Gómez, Juan J. Gaitán, Sergio Asensio, Betty Josefina Mendoza, Sophie Donnet, Fernando T. Maestre. [Global Change Biology, https://doi.org/10.1111/gcb.70345](https://onlinelibrary.wiley.com/doi/10.1111/gcb.70345?af=R)

- [A28] *Hoeffding-type decomposition for U-statistics on bipartite networks* . T. Le Minh, S. Donnet, F. Massol, S. Robin. [Electron. J. Statist. 19(1): 2829-2875 (2025). DOI: 10.1214/25-EJS2402](https://arxiv.org/abs/2308.14518)



- [A27] *The interplay of facilitation and competition drives the emergence of multistability in dryland plant communities*, B. Pichon, I. Gounand, S. Donnet, S. Kéfi. [Ecology, August 2024, Volume 105, Issue 8.](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecy.4369) 

- [A26] *Using the multivariate Hawkes process to study interactions between multiple species from camera trap data* L. Nicvert, S. Donnet, M. Keith, M. Peel, M.J. Somers, L. H. 
Swanepoel, J. Venter,  H. Fritz, and S. Dray.  [Ecology, April 2024, Volume 105, Issue 4 ](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecy.4237)

- [A25] *Learning common structures in a collection of networks. An application to food webs*. S.-C. Chabert-Liddell, P. Barbillon, S. Donnet. [Annals of Applied Statistics, 18(2): 1213-1235 (June 2024).](https://projecteuclid.org/journals/annals-of-applied-statistics/volume-18/issue-2/Learning-common-structures-in-a-collection-of-networks-An-application/10.1214/23-AOAS1831.full)

- [A24] *Linking seed networks and crop diversity contributions to people: a case study in small-scale farming systems in Sahelian Senegal*. Vanesse Labeyrie, Sophie Donnet; Rachel S. Friedman; Ndeye Fatou Faye; Océane Cobelli; Jacopo Baggio; Kailin Kroetz; María R. Felipe-Lucia; Jaime Ashander; Christine Raimond. [Volume 211, October 2023, 103726, Agricultural Systems](https://www.sciencedirect.com/science/article/abs/pii/S0308521X23001312?via%3Dihub)

 

-   [A23] *Expert elicitation and hierarchical Bayesian approach for parametric survival models: An application to Ixodes ricinus ticks exposed to various temperature and relative humidity*. P. Wongnak, S. Bord, S. Donnet, T. Hoch, F. Beugnet , K. Chalvet-Monfray. [Ecological Modelling, Volume 464, February 2022](https://www.sciencedirect.com/science/article/pii/S0304380021003653)

-   [A22] *Impact of the mesoscale structure of a bipartite ecological interaction network on its robustness through a probabilistic modeling*, S.-C. Chabert-Liddell, P. Barbillon, S. Donnet. Published in [Environmetrics, Volume 33, Issue 2](https://onlinelibrary.wiley.com/share/author/QQSDM44WHNCDYVMQJKVT?target=10.1002/env.2709). DOI: 10.1002/env.2709

-   [A21] *Coupling ecological network analysis with high-throughput sequencing-based surveys: lessons from the Next-Generation Biomonitoring project*, M. Dubart, P. Alonso, D. Barroso-Bergada, N. Becker, K. Bethune, D. A. Bohan, C. Boury, M. Cambon, E. Canard, E. Chancerel, J. Chiquet, P. David, N. de Manincor, S. Donnet, A. Duputié, B. Facon, E. Guichoux, T. Le Minh, S. Ortiz-Martínez, L. Piouceau, A. Sacco--Martret de Préville, M. Plantegenest, C. Poux, V. Ravigné, S. Robin, M. Trillat, C. Vacher, C. Vernière, François Massol. [Advances in Ecological Research,  Volume 65, 2021, Pages 367-430](https://www.sciencedirect.com/science/article/abs/pii/S0065250421000222)

-   [A20] *Accelerating Bayesian estimation for network Poisson models using frequentist variational estimates*. Sophie Donnet, Stéphane Robin. [JRSSC, 16 April 2021](https://rss.onlinelibrary.wiley.com/doi/10.1111/rssc.12489). [[Arxiv]](https://arxiv.org/abs/1907.09771).

-   [A19] *A Stochastic Block Model for Multilevel Networks: Application to the Sociology of Organisations*. Saint-Clair Chabert-Liddell, Pierre Barbillon, Sophie Donnet & Emmanuel Lazega [Computational Statistics and Data Analysis, Volume 158, june 2021](https://www.sciencedirect.com/science/article/pii/S016794732100013X?via%3Dihub). [[Arxiv]](https://arxiv.org/abs/1910.10512).

-   [A18] *Block models for multipartite networks. Applications in ecology and ethnobiology*. A. Bar-Hen, P. Barbillon & S. Donnet. [Statistical Modelling, First Published December 18, 2020](https://journals.sagepub.com/doi/abs/10.1177/1471082X20963254). [[Arxiv]](https://arxiv.org/abs/1807.10138)

-   [A17] *Nonparametric Bayesian estimation of multivariate Hawkes processes.* S. Donnet, V. Rivoirard & J. Rousseau. [Annals of Statistics, 2020, Vol. 48, No. 5, 2698-2727](https://projecteuclid.org/download/pdfview_1/euclid.aos/1600480929). [[Arxiv]](https://arxiv.org/abs/1802.05975)

-   [A16] *Effects of competition on collective learning in advice networks*. E. Lazega, A. Bar-Hen, P. Barbillon, S. Donnet. [Social Networks, Volume 47, October 2016, Pages 1--14](https://www.sciencedirect.com/science/article/pii/S0378873316301216) [<i class="fas fa-file-download"></i> pdf](publi/A16_social_networks2016.pdf)

-   [A15] *Stochastic block models for multiplex networks: an application ot multilevel network of researchers*. P. Barbillon, S. Donnet, E. Lazega, A. Bar-Hen. [JRSSA. Volume 180, Issue1, January 2017, Pages 295-314](https://rss.onlinelibrary.wiley.com/doi/full/10.1111/rssa.12193) [[Arxiv]](https://arxiv.org/abs/1501.06444)

-   [A14] \* Posterior concentration rates for empirical Bayes procedures with applications to Dirichlet process mixtures.\* S. Donnet, V. Rivoirard, J. Rousseau, C. Scricciolo. [Bernoulli Journal 24(1): 231-256 (February 2018)](https://projecteuclid.org/journals/bernoulli/volume-24/issue-1/Posterior-concentration-rates-for-empirical-Bayes-procedures-with-applications-to/10.3150/16-BEJ872.full).

-   [A13] S. Donnet, V. Rivoirard, J. Rousseau, C. Scricciolo. Posterior concentration rates for counting processes with Aalen multiplicative intensities. [Bayesian Analysis 12(1): 53-87 (March 2017)](https://projecteuclid.org/journals/bayesian-analysis/volume-12/issue-1/Posterior-Concentration-Rates-for-Counting-Processes-with-Aalen-Multiplicative-Intensities/10.1214/15-BA986.full).

-   [A12] M. Capistran, A. Christen, S. Donnet. Bayesian Analysis of ODE's : solver optimal accuracy and Bayes factors. [Journal of Uncertainty Quantification, 4, 829-849](https://epubs.siam.org/doi/pdf/10.1137/140976777). [<i class="fas fa-file-download"></i> pdf](publi/A12_SIAM_2016.pdf)

-   [A11] S. Donnet, J. Rousseau, J. Bayesian Inference for Partially Observed Branching Processes. [Bayesian Analysis Volume 11, Number 1 (2016), 151-190](https://projecteuclid.org/journals/bayesian-analysis/volume-11/issue-1/Bayesian-Inference-for-Partially-Observed-Multiplicative-Intensity-Processes/10.1214/15-BA940.full)

-   [A10] S. Donnet, Bartolo, R., Fernandes J.M., Cunha J.P., Prado, L. and Merchant, H. Monkeys time their movement pauses and not their movement kinematics during a synchronization-continuation rhythmic task. [Journal Of Neurophysiology, May 2014 ; 111(10), 2138](https://journals.physiology.org/doi/full/10.1152/jn.00802.2013) [<i class="fas fa-file-download"></i> pdf](publi/A10_Journ_Neurophysio_14.pdf)

-   [A9] S. Donnet, A. Samson. Using PMCMC in EM algorithm for stochastic mixed models : theoretical and practical issues. [Journal de la Société Française de Statistique, 155, 49-72, 2014](http://journal-sfds.fr/article/view/269).

-   [A8] S. Donnet, A. Samson. A review on estimation of stochastic differential equations for pharmacokinetic/ pharmacodynamic models. [Advanced Drug Delivery Reviews](https://www.sciencedirect.com/science/article/abs/pii/S0169409X13000501) [<i class="fas fa-file-download"></i> pdf](publi/A08_AdvancesDrugs13.pdf)

-   [A7] I. Albert, S. Donnet, C. Guihenneuc, S. Low-Choy, K. Mengersen, J. Rousseau, Combining expert opinions in prior elicitation (with discussion). [Bayesian Analysis, 7(3), 503-546 (2012)](https://projecteuclid.org/journals/bayesian-analysis/volume-7/issue-3/Combining-Expert-Opinions-in-Prior-Elicitation/10.1214/12-BA717.full)

-   [A6] S. Donnet, J.-M. Marin . An empirical Bayes procedure for the selection of Gaussian graphical models. [Statistics and Computing, 22(5), 1113-1123 (2012)](https://link.springer.com/article/10.1007/s11222-011-9285-5) [<i class="fas fa-file-download"></i> pdf](publi/A06_StatsComp_12.pdf)

-   [A5] S. Donnet , J-L Foulley, A. Samson. Bayesian analysis of growth curves using mixed models defined by stochastic differential equations . [Biometrics, 66(3) :733-741, (2010)](https://pubmed.ncbi.nlm.nih.gov/19912169/) [<i class="fas fa-file-download"></i> pdf](publi/A05_Biometrics10.pdf)

-   [A4] P. Ciuciu, T. Vincent, L. Risser, S. Donnet. A joint detection-estimation framework for analysing within-subject fMRI data. [Journal de la Société Française de Statistiques, Vol. 151, No 1 (2010)](http://journal-sfds.fr/article/view/46)

-   [A3] S. Donnet, A. Samson. Parametric inference for mixed models defined by stochastic differential equations. [ESAIM P&S, 12 :196-218, (2008)](https://www.esaim-ps.org/articles/ps/abs/2008/01/ps0650/ps0650.html) [<i class="fas fa-file-download"></i> pdf](publi/A03_esaim2008.pdf)

-   [A2] S. Donnet, A. Samson. Estimation of parameters in missing data models defined by differential equations. [J. Statist. Plann. Inference 137 (2007), no. 9, 2815--2831](https://www.sciencedirect.com/science/article/abs/pii/S0378375807000353) [<i class="fas fa-file-download"></i> pdf](publi/A02_JSPI.pdf)

-   [A1] S. Donnet, M. Lavielle, and J.-B. Poline. [Are fMRI event related reponses constant across events ?. Neuroimage,Volume 31, Issue 3, 1 (July 2006), 1169 -- 1176](https://www.sciencedirect.com/science/article/abs/pii/S1053811905006555)

<br>

## Book chapters

- [C2] *Seed circulation networks, the missing link between crop diversity and sustainable agriculture*. V. Labeyrie, S. Donnet, S. Caillon, E. Garine, C. Raimond. . [Chapter 3 of the “Handbook of Social Networks and the Environment”](https://www.elgaronline.com/edcollchap/book/9781035318759/chapter3.xml).

-   [C1] J. Aubert, P. Barbillon, S. Donnet, V.Miele. *Chap Modèles à blocs latents pour la détection de structure dans les réseaux écologiques/Statistical Models for Hidden Variables in Ecology*. Available \@ [ISTE](https://onlinelibrary.wiley.com/doi/10.1002/9781119902799.ch6).

<br>

## Working papers 

 

- [W1] *Using deterministic approximations to accelerate SMC for posterior sampling*. S. Donnet, S. Robin. [Working paper](https://arxiv.org/abs/1707.07971)

<br>

## Book reviews and discussions

-   [B3] S. Donnet. Book review of "Stochastic Modelling for Systems Biology (second edition)" by Darren J. Wilkinson. CHANCE 25-4 (Décembre 2012)

-   [B2] S. Donnet. Book review of "Statistical Thinking in Epidemiology" by Yu-Kang Tu and Mark S. Gilthorpe. CHANCE 25-4 (Décembre 2012)

-   [B1] S. Donnet. Book review of "Monte Carlo Simulation for the Pharmaceutical Industry : Concepts, Algorithms, and Case Studies" by Mark Chang. International Statistical Review (Avril 2012)

-   [D1] S. Donnet, A. Samson. Discussion on "Parameter estimation for differential equations : a generalized smoothing approaché" (by Ramsay JO, Hooker G, Campbell D and Cao J), Journal of the Royal Statistical Society : Series B, 69(5) :741-796, (2007)

