---
title: "Softwares"
output: 
  html_document:
   toc: false
   logo: img/Logotype-INRAE.jpg
   number_sections: false
   highlight: tango
   css: style.css
   includes:
     before_body: extlogo.html
---




With my colleagues, I developped 2 <i class="fab fa-r-project"></i>  packages available on the CRAN and on <i class="fab fa-github"></i> GitHub. Both of them deal with statistical learning for network data. *Please contact us for any questions or discussions*. 




 - **GREMLINS** :  S. Donnet, [P. Barbillon](https://mia-ps.inrae.fr/pierre-barbillon). R-package for the statistical inference of multipartite network.
Available on [CRAN](https://cran.r-project.org/web/packages/GREMLINS/index.html) or [github](https ://github.com/GrossSBM/GREMLINS)

 - **sbm** : [J. Chiquet](https://mia-ps.inrae.fr/julien-chiquet), S. Donnet & [P. Barbillon](https://mia-ps.inrae.fr/pierre-barbillon). R-package for Stochastic Blockmodels. Available  [github](https://github.com/GrossSBM/sbm)
or [CRAN](https ://cran.r-project.org/web/packages/sbm/index.html)

 
 
*Packages developed by my students*: 

  - [**colSBM**](https://grosssbm.github.io/colSBM/)  by Saint Clair Chabert-Liddell et Louis Lacoste
  - [**robber**](https://chabert-liddell.github.io/robber/)  by Saint Clair Chabert-Liddell 
  - [**MLVSBM**](https://chabert-liddell.github.io/MLVSBM/)  by Saint Clair Chabert-Liddell  
  - [**multiplexobs**](https://github.com/Chabert-Liddell/multiplexobs)  by Saint Clair Chabert-Liddell (post-doc)
  - [**Auto-encoding-GPS-data**](https://github.com/Chabert-Liddell/Auto-encoding-GPS-data)  by Saint Clair Chabert-Liddell (post-doc)
  - [**colvR**](https://github.com/BBricout/colvR) by Barbara Bricout
 
